// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3VGJn_y4iNrnTi_3wF3djlY9-ssEfPr0',
    appId: '1:751514521651:web:230b6226598c05aff2d346',
    messagingSenderId: '751514521651',
    projectId: 'estacaesp32',
    authDomain: 'estacaesp32.firebaseapp.com',
    databaseURL: 'https://estacaesp32-default-rtdb.firebaseio.com',
    storageBucket: 'estacaesp32.firebasestorage.app',
    measurementId: 'G-2Z2R6254SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk-BzcskO1Mra8JIOjI--Vj7mbWM5rviE',
    appId: '1:751514521651:android:4ae188d2a0355fe0f2d346',
    messagingSenderId: '751514521651',
    projectId: 'estacaesp32',
    databaseURL: 'https://estacaesp32-default-rtdb.firebaseio.com',
    storageBucket: 'estacaesp32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNCZQ0sHjuCOVNscHmj9tNSs7hftMPuJ8',
    appId: '1:751514521651:ios:48670ee67a40db96f2d346',
    messagingSenderId: '751514521651',
    projectId: 'estacaesp32',
    databaseURL: 'https://estacaesp32-default-rtdb.firebaseio.com',
    storageBucket: 'estacaesp32.firebasestorage.app',
    iosBundleId: 'com.example.greenCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNCZQ0sHjuCOVNscHmj9tNSs7hftMPuJ8',
    appId: '1:751514521651:ios:48670ee67a40db96f2d346',
    messagingSenderId: '751514521651',
    projectId: 'estacaesp32',
    databaseURL: 'https://estacaesp32-default-rtdb.firebaseio.com',
    storageBucket: 'estacaesp32.firebasestorage.app',
    iosBundleId: 'com.example.greenCloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3VGJn_y4iNrnTi_3wF3djlY9-ssEfPr0',
    appId: '1:751514521651:web:b458ecf5b8b92a04f2d346',
    messagingSenderId: '751514521651',
    projectId: 'estacaesp32',
    authDomain: 'estacaesp32.firebaseapp.com',
    databaseURL: 'https://estacaesp32-default-rtdb.firebaseio.com',
    storageBucket: 'estacaesp32.firebasestorage.app',
    measurementId: 'G-RZW6J6HPTX',
  );
}
